[package]
name = "git-commit-search"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gcs"
path = "src/main.rs"


[dependencies]
clap = "4.5.23"
colored = "2.1.0"
git2 = "0.19.0"
ignore = "0.4.23"
regex = "1.11.1"
